////////////////////////////////////////////////////////////////
//
//  Name: config_error
//  GitHub repository: https://github.com/2ndSightLab/rust-service.git
//  File: src/service/config/config_errors.rs
//  Copyright: © 2025 2nd Sight Lab, LLC
//
//  Configuration error types
//
//  This software, which includes components generated with the assistance of artificial
//  intelligence, is free for personal, educational, and non-profit use, provided that
//  the included copyright notice is retained in all copies or substantial portions of
//  the software. This license, however, does not grant permission for any commercial
//  use, which requires obtaining a separate commercial license from the author. The
//  software is provided "as is," without any warranty, and the author cannot be held
//  liable for any damages or claims arising from its use. By using this software,
//  all users acknowledge that any potentially uncopyrightable portions generated by
//  AI are governed by the terms of this license as part of the overall work.
//
////////////////////////////////////////////////////////////////

use thiserror::Error;

#[derive(Debug, Error)]
pub enum ConfigError {
    #[error("Cannot determine executable path: {0}")]
    ExecutablePath(#[from] std::io::Error),

    #[error("Cannot determine executable directory")]
    ExecutableDirectory,

    #[error("Cannot canonicalize config path: {0}")]
    CanonicalizePath(std::io::Error),

    #[error("Invalid config path")]
    InvalidPath,

    #[error("Invalid configuration format: {0}")]
    InvalidFormat(#[from] toml::de::Error),

    #[error("Invalid service name characters")]
    InvalidServiceName,

    #[error("Log path must be absolute")]
    LogPathNotAbsolute,

    #[error("Log path not in allowed directory")]
    LogPathNotAllowed,

    #[error("Install and config paths must be absolute")]
    PathsNotAbsolute,

    #[error("Config error: {0}")]
    Generic(String),
}
