////////////////////////////////////////////////////////////////
//
//  Name: mod
//  GitHub repository: https://github.com/2ndSightLab/rust-service.git
//  File: src/service/config/mod.rs
//  Copyright: © 2025 2nd Sight Lab, LLC
//
//  Configuration module declarations
//
//  This software, which includes components generated with the assistance of artificial
//  intelligence, is free for personal, educational, and non-profit use, provided that
//  the included copyright notice is retained in all copies or substantial portions of
//  the software. This license, however, does not grant permission for any commercial
//  use, which requires obtaining a separate commercial license from the author. The
//  software is provided "as is," without any warranty, and the author cannot be held
//  liable for any damages or claims arising from its use. By using this software,
//  all users acknowledge that any potentially uncopyrightable portions generated by
//  AI are governed by the terms of this license as part of the overall work.
//
////////////////////////////////////////////////////////////////

pub mod config_errors;
pub mod config_reader;
pub mod service_config;

pub use config_errors::ConfigError;
pub use config_reader::{load_action_config, load_config};
pub use service_config::Config;
